name: CI - WebApp

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      
      - name: Run Ruff linter
        run: ruff check .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: uv-${{ runner.os }}-${{ hashFiles('**/uv.lock', '**/pyproject.toml') }}
          restore-keys: |
            uv-${{ runner.os }}-
      
      - name: Create virtual environment and install dependencies
        run: |
          uv venv
          uv sync
      
      - name: Run unit tests
        run: uv run pytest tests/routes.py -v
      
      - name: Clean up
        if: always()
        run: |
          rm -rf .venv
          rm -rf ~/.cache/uv